name: CD front

on:
  release:
    types: [published]

jobs:
  deploy-front:
    name: Deploy front to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-front-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-front-

      - name: Configure local swap (Runner)
        run: |
          sudo fallocate -l 4G /swapfile
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile
          sudo sysctl vm.swappiness=10

      - name: Set up SSH Key
        run: |
          echo "${{ secrets.CD_EC2_SSH_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Deploy front to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.CD_EC2_USER }}@${{ secrets.CD_EC2_HOST }} 'source ~/.bashrc && bash ~/projects/aicor/deploy-front.sh'
