name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run tests and code style check
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:10.7
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.CI_DB_ROOT_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.CI_DB_DATABASE }}
          MYSQL_USER: ${{ secrets.CI_DB_USERNAME }}
          MYSQL_PASSWORD: ${{ secrets.CI_DB_PASSWORD }}
        ports:
          - 3306:3306

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: ~/.composer/cache
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Config PHP for Laravel
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          extensions: mbstring, pdo, pdo_mysql, intl, bcmath

      - name: Configure Laravel environment for testing
        run: |
          cd back
          cp .env.example .env
          echo "APP_ENV=testing" >> .env
          echo "APP_KEY=" >> .env
          echo "DB_CONNECTION=mysql" >> .env
          echo "DB_HOST=127.0.0.1" >> .env
          echo "DB_PORT=3306" >> .env
          echo "DB_DATABASE=${{ secrets.CI_DB_DATABASE }}" >> .env
          echo "DB_USERNAME=${{ secrets.CI_DB_USERNAME }}" >> .env
          echo "DB_PASSWORD=${{ secrets.CI_DB_PASSWORD }}" >> .env
          composer install --no-interaction
          php artisan key:generate
          php artisan migrate:fresh --seed
          php artisan test

      - name: Run Pint
        run: |
          cd back
          ./vendor/bin/pint --test

      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install front dependencies
        run: |
          cd front
          npm install

      - name: Run ESLint
        run: |
          cd front
          npm run lint

      - name: Run front tests
        run: |
          cd front
          npm run test
        continue-on-error: false
